export const badges = [
  {
    code: "idea_machine",
    name: "Idea Machine",
    description: "Generated 20 business ideas",
    icon: "lightbulb",
    xpReward: 100,
    condition: { type: "ideas_generated", threshold: 20 },
  },
  {
    code: "first_idea",
    name: "Spark of Genius",
    description: "Generated your first business idea",
    icon: "sparkles",
    xpReward: 25,
    condition: { type: "ideas_generated", threshold: 1 },
  },
  {
    code: "project_starter",
    name: "Project Starter",
    description: "Created your first project",
    icon: "rocket",
    xpReward: 50,
    condition: { type: "projects_created", threshold: 1 },
  },
  {
    code: "multi_project",
    name: "Portfolio Builder",
    description: "Created 5 projects",
    icon: "folder-open",
    xpReward: 150,
    condition: { type: "projects_created", threshold: 5 },
  },
  {
    code: "pitch_master",
    name: "Pitch Master",
    description: "Completed a pitch deck project",
    icon: "presentation",
    xpReward: 200,
    condition: { type: "pitch_deck_completed", threshold: 1 },
  },
  {
    code: "report_writer",
    name: "Report Writer",
    description: "Completed a written report project",
    icon: "file-text",
    xpReward: 200,
    condition: { type: "report_completed", threshold: 1 },
  },
  {
    code: "judge_approved",
    name: "Judge Approved",
    description: "Scored above 90 in judge simulator",
    icon: "trophy",
    xpReward: 300,
    condition: { type: "judge_score_above", threshold: 90 },
  },
  {
    code: "compliance_perfect",
    name: "By The Book",
    description: "Achieved 100% compliance score",
    icon: "check-circle",
    xpReward: 150,
    condition: { type: "compliance_perfect", threshold: 1 },
  },
  {
    code: "feedback_seeker",
    name: "Feedback Seeker",
    description: "Requested AI feedback 10 times",
    icon: "message-circle",
    xpReward: 75,
    condition: { type: "feedback_requested", threshold: 10 },
  },
  {
    code: "market_research_pro",
    name: "Market Research Pro",
    description: "Added real statistics to your project",
    icon: "bar-chart",
    xpReward: 100,
    condition: { type: "statistics_added", threshold: 5 },
  },
  {
    code: "roleplay_ready",
    name: "Roleplay Ready",
    description: "Completed 5 roleplay practice sessions",
    icon: "mic",
    xpReward: 150,
    condition: { type: "roleplay_completed", threshold: 5 },
  },
  {
    code: "streak_3",
    name: "On Fire",
    description: "3-day login streak",
    icon: "flame",
    xpReward: 50,
    condition: { type: "streak_days", threshold: 3 },
  },
  {
    code: "streak_7",
    name: "Dedicated",
    description: "7-day login streak",
    icon: "zap",
    xpReward: 100,
    condition: { type: "streak_days", threshold: 7 },
  },
  {
    code: "streak_30",
    name: "DECA Champion",
    description: "30-day login streak",
    icon: "crown",
    xpReward: 500,
    condition: { type: "streak_days", threshold: 30 },
  },
  {
    code: "early_bird",
    name: "Early Bird",
    description: "Started a project 30+ days before competition",
    icon: "alarm-clock",
    xpReward: 75,
    condition: { type: "early_start", threshold: 30 },
  },
];
